// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using FBKVOControllerNS;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Profile.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Profile.Views
{
	[MvxFromStoryboard(StoryboardName = "Profile")]
    public partial class ContactUsView : MvxViewController<ContactUsViewModel>
	{
        FBKVOController _KVOController;

		public ContactUsView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            NavigationController.NavigationBarHidden = false;

			NavigationController.NavigationBar.Layer.ShadowRadius = 2;
			NavigationController.NavigationBar.Layer.ShadowOffset = new CGSize(0, 2);
			NavigationController.NavigationBar.Layer.ShadowOpacity = 0.25f;

            btnSend.Layer.CornerRadius = btnSend.Bounds.Height / 2;
            textFieldEmail.KeyboardType = UIKeyboardType.EmailAddress;

			_KVOController = new FBKVOController(this);
            _KVOController.Observe(btnSend, "enabled", NSKeyValueObservingOptions.Initial | NSKeyValueObservingOptions.New, UpdateBackgroundForItem);

            var setBind = this.CreateBindingSet<ContactUsView, ContactUsViewModel>();
            setBind.Bind(textFieldEmail).For(vm => vm.Text).To(vm => vm.ContactUs.Email);
            setBind.Bind(textFieldSubject).For(vm => vm.Text).To(vm => vm.ContactUs.Subject);
            setBind.Bind(textViewDescription).For(vm => vm.Text).To(vm => vm.ContactUs.Description);
            //setBind.Bind(btnSend).For(vm => vm.Enabled).To(vm => vm.IsEnableSend);
            setBind.Apply();
		}

		void UpdateBackgroundForItem(NSObject arg0, NSObject arg1, NSDictionary<NSString, NSObject> arg2)
		{
			if (arg1 is UIButton item)
			{
				if (item.Enabled)
				{
                    btnSend.BackgroundColor = UIColor.FromRGB(57, 169, 246);
                    btnSend.Layer.ShadowRadius = 1.5f;
                    btnSend.Layer.ShadowOpacity = 0.25f;
                    btnSend.Layer.ShadowOffset = new CGSize(0, 1.5f);
				}
				else
				{
					btnSend.BackgroundColor = UIColor.FromRGB(214, 222, 230);
					btnSend.Layer.ShadowRadius = 0;
                    btnSend.Layer.ShadowOpacity = 0;
					btnSend.Layer.ShadowOffset = new CGSize(0, 0);
				}
			}
		}

        partial void btnSend_TouchUpInside(NSObject sender)
        {
			var alert = UIAlertController.Create("Send Successful", "", UIAlertControllerStyle.Alert);
			alert.AddAction(UIAlertAction.Create("Ok", UIAlertActionStyle.Default, null));
			PresentViewController(alert, true, null);
		}
	}
}
