// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Profile.ViewModels;
using Naxam.Busuu.iOS.Profile.Common;
using UIKit;
using FBKVOControllerNS;
using Naxam.Busuu.iOS.Core.Converter;

namespace Naxam.Busuu.iOS.Profile.Views
{
    [MvxFromStoryboard(StoryboardName = "Profile")]
    public partial class FriendListView : MvxViewController<FriendListViewModel>
	{
        FBKVOController _KVOController;

		public FriendListView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            viewStatusBar.Layer.ShadowRadius = 2;
            viewStatusBar.Layer.ShadowOpacity = 0.25f;
            viewStatusBar.Layer.ShadowOffset = new CGSize(0, 2);

            btnCloseSeach.ContentEdgeInsets = new UIEdgeInsets(4, 4, 4, 4);

			_KVOController = new FBKVOController(this);
            _KVOController.Observe(btnCloseSeach, "Hidden", NSKeyValueObservingOptions.Initial | NSKeyValueObservingOptions.New, UpdateBackgroundForItem);
            _KVOController.Observe(btnSeach, "Hidden", NSKeyValueObservingOptions.Initial | NSKeyValueObservingOptions.New, UpdateBackgroundForItem);

			var fSource = new FriendListTableViewSource(FriendListTableView);
            var fsSource = new FriendListTableViewSource(FriendSearchTableView);

            var setBinding = this.CreateBindingSet<FriendListView, FriendListViewModel>();
            setBinding.Bind(btnBack).To(vm => vm.BackCommand);
			setBinding.Bind(fSource).To(vm => vm.Friends);
            setBinding.Bind(fsSource).To(vm => vm.FriendsSearch);
            setBinding.Bind(btnSeach).To(vm => vm.SearchCommand);
            setBinding.Bind(btnCloseSeach).To(vm => vm.CloseCommand);
            setBinding.Bind(textFakeFriends).For(vm => vm.Hidden).To(vm => vm.VisibleButtonSearch).WithConversion(nameof(VisibilityToHideConverter));
            setBinding.Bind(btnSeach).For(vm => vm.Hidden).To(vm => vm.VisibleButtonSearch).WithConversion(nameof(VisibilityToHideConverter));
            setBinding.Bind(FriendSearchTableView).For(vm => vm.Hidden).To(vm => vm.VisibleCloseButton).WithConversion(nameof(VisibilityToHideConverter));
            setBinding.Bind(btnCloseSeach).For(vm => vm.Hidden).To(vm => vm.VisibleCloseButton).WithConversion(nameof(VisibilityToHideConverter));
            setBinding.Bind(textFieldSeach).For(vm => vm.Hidden).To(vm => vm.VisibleTextSearch).WithConversion(nameof(VisibilityToHideConverter));
            setBinding.Bind(textFieldSeach).For(vm => vm.Text).To(vm => vm.SearchText);
			setBinding.Apply();

			FriendListTableView.Source = fSource;
            FriendSearchTableView.Source = fsSource;
        }

		void UpdateBackgroundForItem(NSObject arg0, NSObject arg1, NSDictionary<NSString, NSObject> arg2)
		{
			if (arg1 is UIButton item)
			{
                if (btnSeach.Hidden)
                {
					if (item.Hidden)
					{
						textFakeSeach.Hidden = false;
					}
					else
					{
						textFakeSeach.Hidden = true;
					}

                    textFieldSeach.BecomeFirstResponder();
                }
                else
                {
                    textFakeSeach.Hidden = true;

                    textFieldSeach.ResignFirstResponder();
                }
			}
		}
	}
}
