// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Profile.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Profile.Views
{
    [MvxFromStoryboard(StoryboardName = "Profile")]
    public partial class ItWorksView : MvxViewController<ItWorksViewModel>
	{
        string textComplete = "Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. Anh Thao dep trai. ";
        string textPractice = "Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai. Chi Ha xinh gai.";

		public ItWorksView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            NavigationController.NavigationBarHidden = false;

			NavigationController.NavigationBar.Layer.ShadowRadius = 2;
			NavigationController.NavigationBar.Layer.ShadowOffset = new CGSize(0, 2);
			NavigationController.NavigationBar.Layer.ShadowOpacity = 0.25f;

			btnRead.Layer.CornerRadius = btnRead.Bounds.Height / 2;
			btnRead.Layer.ShadowRadius = 2;
			btnRead.Layer.ShadowOpacity = 0.25f;
			btnRead.Layer.ShadowOffset = new CGSize(0, 2);

			var tapViewComplete = new UITapGestureRecognizer(() => {
                if (lblCompleteTopConstraint.Constant < 12)
                {
                    lblComplete.Text = textComplete;
                    lblCompleteTopConstraint.Constant = 12;

					UIView.Animate(0.2, 0, UIViewAnimationOptions.CurveEaseIn, () =>
					{
                        imgComplete.Transform = CGAffineTransform.MakeRotation((nfloat)Math.PI);
                    }, null);
                }
                else
                {
					lblComplete.Text = "";
					lblCompleteTopConstraint.Constant = 0;

					UIView.Animate(0.2, 0, UIViewAnimationOptions.CurveEaseIn, () =>
					{
						imgComplete.Transform = CGAffineTransform.MakeRotation(0);
					}, null);
                }
			});

			var tapViewPractice = new UITapGestureRecognizer(() => {
                if (lblPracticeTopConstraint.Constant < 12)
				{
                    lblPractice.Text = textPractice;
                    lblPracticeTopConstraint.Constant = 12;

					UIView.Animate(0.2, 0, UIViewAnimationOptions.CurveEaseIn, () =>
					{
                        imgPractice.Transform = CGAffineTransform.MakeRotation((nfloat)Math.PI);
					}, null);
				}
				else
				{
                    lblPractice.Text = "";
                    lblPracticeTopConstraint.Constant = 0;

					UIView.Animate(0.2, 0, UIViewAnimationOptions.CurveEaseIn, () =>
					{
                        imgPractice.Transform = CGAffineTransform.MakeRotation(0);
					}, null);
				}
			});

            viewComplete.AddGestureRecognizer(tapViewComplete);
            viewPractice.AddGestureRecognizer(tapViewPractice);

            var myTextHtml = System.IO.File.ReadAllText("htmlcuatoi.html");

            lblHtml.Text = myTextHtml;

			var attr = new NSAttributedStringDocumentAttributes();
			var nsError = new NSError();
			attr.DocumentType = NSDocumentType.HTML;

            lblHtml.AttributedText = new NSAttributedString(myTextHtml, attr, ref nsError);
		}

        partial void btnRead_TouchUpInside(NSObject sender)
        {
            var myurl = new NSUrl("http://naxam.net/");
            UIApplication.SharedApplication.OpenUrl(myurl);
        }
	}
}
