// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Profile.ViewModels;

namespace Naxam.Busuu.iOS.Profile.Views
{
    [MvxFromStoryboard(StoryboardName = "Profile")]
    public partial class NotificationSettingView : MvxViewController<NotificationSettingViewModel>
    {
        public NotificationSettingView (IntPtr handle) : base (handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.NavigationController.NavigationBarHidden = false;

            NavigationController.NavigationBar.Layer.ShadowRadius = 2;
            NavigationController.NavigationBar.Layer.ShadowOffset = new CGSize(0, 2);
            NavigationController.NavigationBar.Layer.ShadowOpacity = 0.25f;

            var setBind = this.CreateBindingSet<NotificationSettingView, NotificationSettingViewModel>();
            setBind.Bind(switchPrivateMode).To(vm => vm.IsPrivateMode);
            setBind.Bind(switchNotifications).To(vm => vm.TurnOnNotification);
            setBind.Bind(switchFriendRequests).To(vm => vm.TurnOnFriendRequests);
            setBind.Bind(switchReplies).To(vm => vm.TurnOnReplies);
            setBind.Bind(switchCorrectionAdded).To(vm => vm.TurnOnCorrectionAdded);
            setBind.Bind(switchCorrectionReceived).To(vm => vm.TurnOnCorrectionReceived);
            setBind.Bind(switchCorrectionRequest).To(vm => vm.TurnOnCorrectionRequest);
            setBind.Bind(switchFriendRequests).For(vm => vm.Enabled).To(vm => vm.TurnOnNotification);
            setBind.Bind(switchReplies).For(vm => vm.Enabled).To(vm => vm.TurnOnNotification);
            setBind.Bind(switchCorrectionAdded).For(vm => vm.Enabled).To(vm => vm.TurnOnNotification);
            setBind.Bind(switchCorrectionReceived).For(vm => vm.Enabled).To(vm => vm.TurnOnNotification);
            setBind.Bind(switchCorrectionRequest).For(vm => vm.Enabled).To(vm => vm.TurnOnNotification);
            setBind.Apply();
        }
    }
}
