// This file has been autogenerated from a class added in the UI designer.

using System;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using Naxam.Busuu.iOS.Profile.Common;
using Naxam.Busuu.Profile.ViewModels;
using Naxam.Busuu.iOS.Core.Converter;

namespace Naxam.Busuu.iOS.Profile.Views
{
    [MvxFromStoryboard(StoryboardName = "Profile")]
    public partial class SettingCountryView : MvxViewController<SettingCountryViewModel>
	{
		public SettingCountryView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            viewAppBar.Layer.ShadowRadius = 2;
            viewAppBar.Layer.ShadowOpacity = 0.25f;
			viewAppBar.Layer.ShadowOffset = new CoreGraphics.CGSize(0, 2);

			var cSource = new CountryTableViewSource(CountryTableView);

			var setBinding = this.CreateBindingSet<SettingCountryView, SettingCountryViewModel>();
            setBinding.Bind(btnCancel).To(vm => vm.CancelCommand);
            setBinding.Bind(btnDone).To(vm => vm.DoneCommand);
            setBinding.Bind(btnDone).For(vm => vm.Hidden).To(vm => vm.VisibleDoneButton).WithConversion(nameof(VisibilityToHideConverter));
			setBinding.Bind(cSource).To(vm => vm.Countries);
            setBinding.Bind(cSource).For(vm => vm.SelectedItem).To(vm => vm.Value);
			setBinding.Apply();

			CountryTableView.Source = cSource;
        }
	}
}
