// This file has been autogenerated from a class added in the UI designer.

using System;
using FFImageLoading;
using FFImageLoading.Work;
using Foundation;
using UIKit;

namespace Naxam.Busuu.iOS.Profile.Views
{
	public partial class ShowUserAvatarView : UIViewController
	{
		public ShowUserAvatarView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            //var data = NSData.FromUrl(new NSUrl("https://scontent.fhan2-1.fna.fbcdn.net/v/t1.0-9/16508930_1170067123106485_5721616632039463605_n.jpg?oh=4dc4296fe19f805057c4ff9834f10224&oe=5A342AE1"));
            //imgUser.Image = UIImage.LoadFromData(data);

            ImageService.Instance.LoadUrl("https://scontent.fhan2-1.fna.fbcdn.net/v/t1.0-9/16508930_1170067123106485_5721616632039463605_n.jpg?oh=4dc4296fe19f805057c4ff9834f10224&oe=5A342AE1").
						ErrorPlaceholder("user_avatar_placeholder.png", ImageSource.ApplicationBundle).
						LoadingPlaceholder("user_avatar_placeholder.png", ImageSource.ApplicationBundle).
                        Into(imgUser);
        }

        partial void btnBack_TouchUpInside(NSObject sender)
        {
            this.NavigationController.PopViewController(true);
        }
	}
}
