// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.iOS.Views;
using MvvmCross.iOS.Views.Presenters.Attributes;
using Naxam.Busuu.iOS.Learning.Common;
using Naxam.Busuu.Learning.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Learning.Views
{
    [MvxFromStoryboard(StoryboardName = "Learning")]
    [MvxModalPresentation(WrapInNavigationController = true)]
    public partial class ChangeLanguageView : MvxViewController<ChangeLanguageViewModel>
	{
		public ChangeLanguageView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			var btnBack = new UIBarButtonItem()
			{
				Image = UIImage.FromBundle("iconBack")
			};

			NavigationItem.SetLeftBarButtonItem(btnBack, false);
            NavigationItem.Title = "Languages";

            ChangeLanguageDataSource cSource = new ChangeLanguageDataSource(ChangeLanguageCollectionView, (NSString)"ChangeLanguageCollectionViewCell");

			var setBinding = this.CreateBindingSet<ChangeLanguageView, ChangeLanguageViewModel>();
			setBinding.Bind(btnBack).For("Clicked").To(vm => vm.GoBackCommand);
            setBinding.Bind(cSource).To(vm => vm.Languages);
            setBinding.Apply();

            ChangeLanguageCollectionView.Source = cSource;
        }
	}
}
