// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using MvvmCross.iOS.Views.Presenters.Attributes;
using Naxam.Busuu.iOS.Learning.Common;
using Naxam.Busuu.Learning.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Learning.Views
{
	[MvxFromStoryboard(StoryboardName = "Learning")]
	[MvxModalPresentation(WrapInNavigationController = true)]
	public partial class DialogueView : MvxViewController<DialogueViewModel>, IAnswerClick
	{
		public DialogueView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            NavigationController.NavigationBarHidden = true;

            btnStart.Layer.CornerRadius = btnStart.Layer.Bounds.Height / 2;
            btnStart.Layer.ShadowRadius = 2;
            btnStart.Layer.ShadowOpacity = 0.25f;
            btnStart.Layer.ShadowOffset = new CGSize(0, 2);

			//var setBinding = this.CreateBindingSet<DialogueView, DialogueViewModel>();
            //setBinding.Bind(btnStart).To(vm => vm.StartCommand).Apply();

            btnStart.TouchUpInside += BtnStart_TouchUpInside;
        }

        void BtnStart_TouchUpInside(object sender, EventArgs e)
        {
			var alert = UIAlertController.Create("Sorry", "The functions are in the process of construction", UIAlertControllerStyle.Alert);
			alert.AddAction(UIAlertAction.Create("Ok", UIAlertActionStyle.Default, delegate {
				this.ViewModel.GoBackCommand.Execute();
			}));
			PresentViewController(alert, true, null);
		}

        public void DidAnswer(UIView view)
        {
            throw new NotImplementedException();
        }

        public void NextAnswer(UIView view)
        {
            throw new NotImplementedException();
        }

        public void GoLearnView(UIView view)
        {
            this.ViewModel.GoBackCommand.Execute();
        }

        public void ResetExercise(UIView view)
        {
            throw new NotImplementedException();
        }
    }
}
