// This file has been autogenerated from a class added in the UI designer.

using System;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using Naxam.Busuu.Core.Models;

namespace Naxam.Busuu.iOS.Profile.Cells
{
    public partial class CountryTableViewCell : MvxTableViewCell
	{
		public CountryTableViewCell (IntPtr handle) : base (handle)
		{
			this.DelayBind(() =>
			{
                var setBinding = this.CreateBindingSet<CountryTableViewCell, CountryModel>();
				setBinding.Bind(lblCountry).To(n => n.Country);
				setBinding.Apply();
			});
		}
	}
}
