// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using Naxam.Busuu.Core.Models;
using UIKit;

namespace Naxam.Busuu.iOS.Profile.Cells
{
	public partial class FriendListCell : MvxTableViewCell
	{
        readonly MvxImageViewLoader _loaderImageUser;

		public FriendListCell (IntPtr handle) : base (handle)
		{
			_loaderImageUser = new MvxImageViewLoader(() => this.imgUser);
			_loaderImageUser.DefaultImagePath = "res:user_avatar_placeholder.png";

			this.DelayBind(() =>
			{
                var setBinding = this.CreateBindingSet<FriendListCell, UserModel>();
                setBinding.Bind(_loaderImageUser).To(n => n.Photo);
                setBinding.Bind(lblUserName).To(n => n.Name);
				setBinding.Apply();
			});
		}
	}
}
