// This file has been autogenerated from a class added in the UI designer.

using System;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using Naxam.Busuu.Core.Models;
using Naxam.Busuu.iOS.Core.Converter;
using Naxam.Busuu.iOS.Core.Converter.LanguageSpeakCell;

namespace Naxam.Busuu.iOS.Profile.Cells
{
    public partial class LanguageSpeakCell : MvxTableViewCell
	{
        readonly MvxImageViewLoader _loaderImgLanaguage;

		public LanguageSpeakCell (IntPtr handle) : base (handle)
		{
			_loaderImgLanaguage = new MvxImageViewLoader(() => this.imgLanguageSpeak);

			this.DelayBind(() =>
			{
                var setBinding = this.CreateBindingSet<LanguageSpeakCell, LanguageModel>();
                setBinding.Bind(_loaderImgLanaguage).To(n => n.Flag).WithConversion(nameof(ImageUriConverter));
                setBinding.Bind(lblLanguageSpeak).To(n => n.Language);
                setBinding.Bind(lblLever).To(n => n.LanguageLevel);
                setBinding.Bind(lblLever).For(n => n.Hidden).To(n => n.IsCurrent).WithConversion(nameof(VisibilityToHideConverter));
                setBinding.Bind(imgYes).For(n => n.Hidden).To(n => n.IsCurrent).WithConversion(nameof(VisibilityToHideConverter));
                setBinding.Bind(lblLeverHeightConstrait).For(n => n.Constant).To(n => n.IsCurrent).WithConversion(nameof(lblLeverHeightConverter));
                setBinding.Bind(lblLeverTopContraint).For(n => n.Constant).To(n => n.IsCurrent).WithConversion(nameof(lblLeverTopConverter));
                setBinding.Apply();
			});
		}

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();

            imgLanguageSpeak.Layer.CornerRadius = imgLanguageSpeak.Frame.Width / 2;
		}
	}
}
