// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using MvvmCross.iOS.Views;
using MvvmCross.iOS.Views.Presenters.Attributes;
using Naxam.Busuu.Core.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Core.Views
{
    [MvxFromStoryboard(StoryboardName = "Core")]
    [MvxChildPresentation]
    public partial class BuyPremium : MvxViewController<BuyPremiumViewModel>
    {
        public BuyPremium(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            //NavigationItem.Title = "Premium";
            InitSubviews(new[] {monthView, sixMonthView});
            //NavigationItem.LeftBarButtonItem.Title = "";
        }

        void InitSubviews(UIView[] views)
        {
            foreach (var view in views)
            {
                view.BackgroundColor = UIColor.White;
                view.Layer.ShadowColor = UIColor.LightGray.CGColor;
                view.Layer.ShadowOpacity = 0.8f;
                view.Layer.ShadowRadius = 3.0f;
                view.Layer.ShadowOffset = new CGSize(1.0, 1.0);
            }
        }
    }
}
