// This file has been autogenerated from a class added in the UI designer.

using System;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using Naxam.Busuu.iOS.Core.Converter;
using Naxam.Busuu.Learning.Models;

namespace Naxam.Busuu.iOS.Learning.Cells
{
    public partial class SubLessonTableViewCell : MvxTableViewCell
    {
        public event EventHandler<ExerciseClickEventArg> ExerciseClick;

        public int LessonId;

        public int TopicId;

        public SubLessonTableViewCell(IntPtr handle) : base(handle)
        {
            this.DelayBind(() =>
          {
              var bindingSet = this.CreateBindingSet<SubLessonTableViewCell, TopicModel>();
                bindingSet.Bind(lbTime).To(m => m.Time).WithConversion(nameof(AddMinutesValueConverter));
              bindingSet.Bind(lbTitle).To(m => m.Toppic);
                bindingSet.Bind(ContentView.Layer).For("LayerBackgroundColor").To(m => m.Color).WithConversion(nameof(HexToBrighterUIColorValueConverter));
              bindingSet.Bind(exerciseView).For(x => x.Exercises).To(m => m.Exercises);
              bindingSet.Apply();
          });
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
            exerciseView.ExerciseClick += ExerciseView_ExerciseClick;
        }

        void ExerciseView_ExerciseClick(object sender, ExerciseClickEventArg e)
        {
			ExerciseClick?.Invoke(this, new ExerciseClickEventArg
			{
				LessonIndex = LessonId,
				TopicIndex = TopicId,
				Exercise = e.Exercise,
				ExerciseIndex = e.ExerciseIndex
			});
        }
    }
}
