// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using Naxam.Busuu.iOS.Notification.Common;
using Naxam.Busuu.Notification.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Notification.Views
{
    [MvxFromStoryboard(StoryboardName = "Notification")]
    public partial class FriendRequestView : MvxViewController<FriendRequestViewModel>
	{
		public FriendRequestView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.NavigationController.NavigationBar.Layer.ShadowRadius = 2;
            this.NavigationController.NavigationBar.Layer.ShadowOpacity = 0.25f;
            this.NavigationController.NavigationBar.Layer.ShadowOffset = new CGSize(0, 2);
             
			var btnBack = new UIBarButtonItem()
			{
				Image = UIImage.FromBundle("iconBack")
			};

			NavigationItem.SetLeftBarButtonItem(btnBack, false);

            var fSource = new FriendRequestTableViewSource(FriendRequestTableView);

            var setBinding = this.CreateBindingSet<FriendRequestView, FriendRequestViewModel>();
			setBinding.Bind(btnBack).For("Clicked").To(vm => vm.GoBackCommand);
			setBinding.Bind(fSource).To(vm => vm.FriendsRequest);
			setBinding.Bind(fSource).For(nameof(FriendRequestTableViewSource.ViewFriendsYesCommand)).To(vm => vm.ViewFriendsYesCommand);
            setBinding.Bind(fSource).For(nameof(FriendRequestTableViewSource.ViewFriendsNoCommand)).To(vm => vm.ViewFriendsNoCommand);
			setBinding.Apply();

            FriendRequestTableView.Source = fSource;
        }
	}
}
